// tom-weatherhead/thaw-grammar/src/common/symbols.ts
'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
exports.Symbol = void 0;
var Symbol;
(function (Symbol) {
    Symbol[Symbol["UndefinedSymbol"] = 0] = "UndefinedSymbol";
    Symbol[Symbol["Lambda"] = 1] = "Lambda";
    Symbol[Symbol["Dot"] = 2] = "Dot";
    Symbol[Symbol["terminalBegin"] = 3] = "terminalBegin";
    Symbol[Symbol["terminalEnd"] = 4] = "terminalEnd";
    Symbol[Symbol["terminalAssign"] = 5] = "terminalAssign";
    Symbol[Symbol["terminalSemicolon"] = 6] = "terminalSemicolon";
    Symbol[Symbol["terminalRead"] = 7] = "terminalRead";
    Symbol[Symbol["terminalWrite"] = 8] = "terminalWrite";
    Symbol[Symbol["terminalLeftBracket"] = 9] = "terminalLeftBracket";
    Symbol[Symbol["terminalRightBracket"] = 10] = "terminalRightBracket";
    Symbol[Symbol["terminalComma"] = 11] = "terminalComma";
    Symbol[Symbol["terminalID"] = 12] = "terminalID";
    Symbol[Symbol["terminalVariable"] = 13] = "terminalVariable";
    Symbol[Symbol["terminalIntegerLiteral"] = 14] = "terminalIntegerLiteral";
    Symbol[Symbol["terminalFloatLiteral"] = 15] = "terminalFloatLiteral";
    Symbol[Symbol["terminalStringLiteral"] = 16] = "terminalStringLiteral";
    Symbol[Symbol["terminalPlus"] = 17] = "terminalPlus";
    Symbol[Symbol["terminalMinus"] = 18] = "terminalMinus";
    Symbol[Symbol["terminalCond"] = 19] = "terminalCond";
    Symbol[Symbol["terminalLet"] = 20] = "terminalLet";
    Symbol[Symbol["terminalLetStar"] = 21] = "terminalLetStar";
    // LISP terminals
    Symbol[Symbol["terminalDefine"] = 22] = "terminalDefine";
    Symbol[Symbol["terminalIf"] = 23] = "terminalIf";
    Symbol[Symbol["terminalWhile"] = 24] = "terminalWhile";
    Symbol[Symbol["terminalSet"] = 25] = "terminalSet";
    Symbol[Symbol["terminalMultiply"] = 26] = "terminalMultiply";
    Symbol[Symbol["terminalDivide"] = 27] = "terminalDivide";
    Symbol[Symbol["terminalEquals"] = 28] = "terminalEquals";
    Symbol[Symbol["terminalLessThan"] = 29] = "terminalLessThan";
    Symbol[Symbol["terminalGreaterThan"] = 30] = "terminalGreaterThan";
    Symbol[Symbol["terminalPrint"] = 31] = "terminalPrint";
    Symbol[Symbol["terminalCons"] = 32] = "terminalCons";
    Symbol[Symbol["terminalCar"] = 33] = "terminalCar";
    Symbol[Symbol["terminalCdr"] = 34] = "terminalCdr";
    Symbol[Symbol["terminalNumberPred"] = 35] = "terminalNumberPred";
    Symbol[Symbol["terminalSymbolPred"] = 36] = "terminalSymbolPred";
    Symbol[Symbol["terminalListPred"] = 37] = "terminalListPred";
    Symbol[Symbol["terminalNullPred"] = 38] = "terminalNullPred";
    Symbol[Symbol["terminalStringPred"] = 39] = "terminalStringPred";
    Symbol[Symbol["terminalApostrophe"] = 40] = "terminalApostrophe";
    Symbol[Symbol["terminalDot"] = 41] = "terminalDot";
    Symbol[Symbol["terminalList"] = 42] = "terminalList";
    Symbol[Symbol["terminalRplaca"] = 43] = "terminalRplaca";
    Symbol[Symbol["terminalRplacd"] = 44] = "terminalRplacd";
    Symbol[Symbol["terminalDefineMacro"] = 45] = "terminalDefineMacro";
    Symbol[Symbol["terminalQuoteKeyword"] = 46] = "terminalQuoteKeyword";
    Symbol[Symbol["terminalRandom"] = 47] = "terminalRandom";
    Symbol[Symbol["terminalToString"] = 48] = "terminalToString";
    Symbol[Symbol["terminalListToString"] = 49] = "terminalListToString";
    Symbol[Symbol["terminalStringToList"] = 50] = "terminalStringToList";
    Symbol[Symbol["terminalStringToSymbol"] = 51] = "terminalStringToSymbol";
    Symbol[Symbol["terminalSin"] = 52] = "terminalSin";
    Symbol[Symbol["terminalCos"] = 53] = "terminalCos";
    Symbol[Symbol["terminalTan"] = 54] = "terminalTan";
    Symbol[Symbol["terminalPow"] = 55] = "terminalPow";
    Symbol[Symbol["terminalExp"] = 56] = "terminalExp";
    Symbol[Symbol["terminalLn"] = 57] = "terminalLn";
    Symbol[Symbol["terminalFloor"] = 58] = "terminalFloor";
    Symbol[Symbol["terminalAtan2"] = 59] = "terminalAtan2";
    Symbol[Symbol["terminalThrow"] = 60] = "terminalThrow";
    Symbol[Symbol["terminalStringLessThan"] = 61] = "terminalStringLessThan";
    // Scheme terminals
    Symbol[Symbol["terminalPrimOpPred"] = 62] = "terminalPrimOpPred";
    Symbol[Symbol["terminalClosurePred"] = 63] = "terminalClosurePred";
    Symbol[Symbol["terminalLambdaKeyword"] = 64] = "terminalLambdaKeyword";
    Symbol[Symbol["terminalLetRec"] = 65] = "terminalLetRec";
    Symbol[Symbol["terminalCallCC"] = 66] = "terminalCallCC";
    Symbol[Symbol["terminalEOF"] = 67] = "terminalEOF";
    // Non-terminal symbols
    Symbol[Symbol["nonterminalStart"] = 68] = "nonterminalStart";
    Symbol[Symbol["nonterminalProgram"] = 69] = "nonterminalProgram";
    Symbol[Symbol["nonterminalStatementList"] = 70] = "nonterminalStatementList";
    Symbol[Symbol["nonterminalStatementTail"] = 71] = "nonterminalStatementTail";
    Symbol[Symbol["nonterminalStatement"] = 72] = "nonterminalStatement";
    Symbol[Symbol["nonterminalIDList"] = 73] = "nonterminalIDList";
    Symbol[Symbol["nonterminalIDTail"] = 74] = "nonterminalIDTail";
    Symbol[Symbol["nonterminalExprList"] = 75] = "nonterminalExprList";
    Symbol[Symbol["nonterminalExprTail"] = 76] = "nonterminalExprTail";
    Symbol[Symbol["nonterminalExpression"] = 77] = "nonterminalExpression";
    Symbol[Symbol["nonterminalPrimaryTail"] = 78] = "nonterminalPrimaryTail";
    Symbol[Symbol["nonterminalPrimary"] = 79] = "nonterminalPrimary";
    Symbol[Symbol["nonterminalAddOp"] = 80] = "nonterminalAddOp";
    // Chapter 1 non-terminals
    Symbol[Symbol["nonterminalBracketedEntity"] = 81] = "nonterminalBracketedEntity";
    // LISP non-terminals
    Symbol[Symbol["nonterminalInput"] = 82] = "nonterminalInput";
    Symbol[Symbol["nonterminalFunDef"] = 83] = "nonterminalFunDef";
    Symbol[Symbol["nonterminalFunction"] = 84] = "nonterminalFunction";
    Symbol[Symbol["nonterminalArgList"] = 85] = "nonterminalArgList";
    Symbol[Symbol["nonterminalVariableList"] = 86] = "nonterminalVariableList";
    Symbol[Symbol["nonterminalVariable"] = 87] = "nonterminalVariable";
    Symbol[Symbol["nonterminalValue"] = 88] = "nonterminalValue";
    Symbol[Symbol["nonterminalBracketedExpression"] = 89] = "nonterminalBracketedExpression";
    Symbol[Symbol["nonterminalExpressionList"] = 90] = "nonterminalExpressionList";
    Symbol[Symbol["nonterminalOptr"] = 91] = "nonterminalOptr";
    Symbol[Symbol["nonterminalValueOp"] = 92] = "nonterminalValueOp";
    Symbol[Symbol["nonterminalQuotedConst"] = 93] = "nonterminalQuotedConst";
    Symbol[Symbol["nonterminalSExpression"] = 94] = "nonterminalSExpression";
    Symbol[Symbol["nonterminalSExpressionList"] = 95] = "nonterminalSExpressionList";
    Symbol[Symbol["nonterminalSymbol"] = 96] = "nonterminalSymbol";
    Symbol[Symbol["nonterminalMacroDef"] = 97] = "nonterminalMacroDef";
    Symbol[Symbol["nonterminalExprPairList"] = 98] = "nonterminalExprPairList";
    Symbol[Symbol["nonterminalLetKeyword"] = 99] = "nonterminalLetKeyword";
    Symbol[Symbol["nonterminalVarExprList"] = 100] = "nonterminalVarExprList";
    Symbol[Symbol["nonterminalBracketedInput"] = 101] = "nonterminalBracketedInput";
    Symbol[Symbol["nonterminalUnbracketedInput"] = 102] = "nonterminalUnbracketedInput";
    Symbol[Symbol["nonterminalSExpressionListTail"] = 103] = "nonterminalSExpressionListTail";
})(Symbol = exports.Symbol || (exports.Symbol = {}));
